language: node_js
sudo: required
dist: trusty
node_js:
- node
notifications:
  slack: unolabs:cbusXPH6pBwZ35rVDzi4k4ve
addons:
  firefox: 'latest'
env: TZ=Mexico/General
matrix:
  include:
    - env: 
      - CHROME_BIN=/usr/bin/google-chrome
      - FF=false
    - env: FF=true
install:
- npm install
- bower update
before_install:
- if [[ "$FF" = "false" ]]; then sudo apt-get update; fi
- if [[ "$FF" = "false" ]]; then sudo apt-get install -y libappindicator1 fonts-liberation; fi
- if [[ "$FF" = "false" ]]; then wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb; fi
- if [[ "$FF" = "false" ]]; then sudo dpkg -i google-chrome*.deb; fi
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- npm test
- chmod +x ./publish.sh
- ./publish.sh
env:
  global:
    secure: beog7sTAvmzWIYC9fEFCVr/ok60aU796/t2cO6oaHpsZxqwM9u2PYBae3o4gJsrZywv9yfKzUku5j/ugHYtrVTt6edCZOGydOwm1vjZINrxvf8zf+dMUicOIu1SfiPAMYbCwq8xlB/MeyzTggkcxymHcr1ARTeqjXpC8XJDFCnQ=
