language: node_js
sudo: required
dist: trusty
node_js:
- node
notifications:
  slack: unolabs:cbusXPH6pBwZ35rVDzi4k4ve
addons:
  firefox: 'latest'
  chrome: 'latest'
install:
- npm install
- bower update
before_script:
- if [[ $TRAVIS_OS_NAME == "linux" ]]; then export DISPLAY=:99.0; fi
- if [[ $TRAVIS_OS_NAME == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi
script:
- grunt min
- npm test
- chmod +x ./publish.sh
- ./publish.sh
env:
  global:
    secure: beog7sTAvmzWIYC9fEFCVr/ok60aU796/t2cO6oaHpsZxqwM9u2PYBae3o4gJsrZywv9yfKzUku5j/ugHYtrVTt6edCZOGydOwm1vjZINrxvf8zf+dMUicOIu1SfiPAMYbCwq8xlB/MeyzTggkcxymHcr1ARTeqjXpC8XJDFCnQ=
