language: csharp
solution: Unosquare.Tubular.Lib.sln
notifications:
  slack: unolabs:cbusXPH6pBwZ35rVDzi4k4ve
addons:
  firefox: "49.0"
env:
  - TRAVIS_NODE_VERSION="6"
mono: latest
install:
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then brew cask install google-chrome; fi
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - nuget install NUnit.ConsoleRunner -OutputDirectory testrunner
  - nuget restore Unosquare.Tubular.Lib.sln
  - npm install
before_script:
  - touch ./src/Unosquare.Tubular/Javascript/tubular-bundle.js
  - touch ./src/Unosquare.Tubular/Javascript/tubular-bundle.min.js
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then export DISPLAY=:99.0; fi
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi
script:
  - xbuild /p:Configuration=Release Unosquare.Tubular.Lib.sln
  - mono --debug ./testrunner/NUnit.ConsoleRunner.*/tools/nunit3-console.exe --process=Single ./test/Unosquare.Tubular.Tests/bin/Release/Unosquare.Tubular.Tests.dll
  - ./node_modules/protractor/bin/webdriver-manager update
  - grunt test
