language: csharp
solution: Unosquare.Tubular.Lib.sln
notifications:
  slack: unolabs:cbusXPH6pBwZ35rVDzi4k4ve
matrix:
  include:
    - os: linux
      dotnet: 1.0.0-preview2-003131
      mono: none
      env: DOTNETCORE=1
      dist: trusty
      sudo: false
    - os: linux
      mono: 4.2.1
      env: TRAVIS_NODE_VERSION=4
    - os: osx
      dotnet: 1.0.0-preview2-003131
      mono: none
      env: DOTNETCORE=1
install:
  - if [[ $DOTNETCORE == "" ]]; then nuget install NUnit.ConsoleRunner -OutputDirectory testrunner; fi
  - if [[ $DOTNETCORE == "1" ]]; then dotnet restore; else nuget restore Unosquare.Tubular.Lib.sln; fi 
  - if [[ $DOTNETCORE == "" ]]; then rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION; fi
  - npm install
before_script:
  - touch ./src/Unosquare.Tubular/Javascript/tubular-bundle.js
  - touch ./src/Unosquare.Tubular/Javascript/tubular-bundle.min.js
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then export DISPLAY=:99.0; fi
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then sh -e /etc/init.d/xvfb start; fi
script:
  - if [[ $DOTNETCORE == "" ]]; then xbuild /p:"TargetFrameworkVersion=v4.5;Configuration=Release" Unosquare.Tubular.Lib.sln; fi
  - if [[ $DOTNETCORE == "1" ]]; then dotnet test ./test/Unosquare.Tubular.Tests -f netcoreapp1.0; else mono --debug ./testrunner/NUnit.ConsoleRunner.*/tools/nunit3-console.exe --process=Single ./test/Unosquare.Tubular.Tests/bin/Release/Unosquare.Tubular.Tests.dll; fi
  - npm test
