language: csharp
solution: Unosquare.Tubular.Lib.sln
mono:
  - latest
  - 4.2.1
install:
  - nuget restore Unosquare.Tubular.Lib.sln
  - nuget install NUnit.ConsoleRunner -OutputDirectory testrunner
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - npm install
env:
  - TRAVIS_NODE_VERSION="4"
before_script:
  - touch ./Unosquare.Tubular/Javascript/tubular-bundle.js
  - touch ./Unosquare.Tubular/Javascript/tubular-bundle.min.js
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - xbuild /p:Configuration=Release Unosquare.Tubular.Lib.sln
  - mono --debug ./testrunner/NUnit.ConsoleRunner.*/tools/nunit3-console.exe --process=Single ./Unosquare.Tubular.Tests/bin/Release/Unosquare.Tubular.Tests.dll
  - ./node_modules/protractor/bin/webdriver-manager update
  - grunt test
