language: node_js
sudo: required
node_js:
  - "node"
notifications:
  slack: unolabs:cbusXPH6pBwZ35rVDzi4k4ve
addons:
  firefox: "51.0"
install:
  - npm install
  - bower update
before_script:
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then export DISPLAY=:99.0; fi
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi
script:
  - grunt min
  - npm test
  - chmod +x ./publish.sh
  - ./publish.sh
