language: csharp
solution: Unosquare.Tubular.Lib.sln
notifications:
  slack: unolabs:cbusXPH6pBwZ35rVDzi4k4ve
addons:
  firefox: "51.0"
env:
  - TRAVIS_NODE_VERSION="6"
mono: latest
sudo: required
install:
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then brew cask install google-chrome; fi
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - nuget install NUnit.ConsoleRunner -OutputDirectory testrunner
  - nuget restore Unosquare.Tubular.Lib.sln
  - npm install
  - bower update
  - ./node_modules/protractor/bin/webdriver-manager update
  - cd /home/travis/build/unosquare/tubular/node_modules/protractor/node_modules/webdriver-manager/selenium/
  - curl -o geckodriver-v0.14.0.tar.gz https://github.com/mozilla/geckodriver/releases/download/v0.14.0/geckodriver-v0.14.0-linux64.tar.gz
  - gunzip geckodriver-v0.14.0.tar.gz
  - tar xvf geckodriver-v0.14.0.tar
  - mv geckodriver-v0.14.0 geckodriver-v0.15.0
  - chmod +x geckodriver-v0.15.0
  - cd /home/travis/build/unosquare/tubular
before_script:
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then export DISPLAY=:99.0; fi
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi
script:
  - grunt min
  - xbuild /p:Configuration=Release Unosquare.Tubular.Lib.sln
  - mono --debug ./testrunner/NUnit.ConsoleRunner.*/tools/nunit3-console.exe --process=Single ./test/Unosquare.Tubular.Tests/bin/Release/Unosquare.Tubular.Tests.dll
  - npm test
  - chmod +x ./publish.sh
  - ./publish.sh
