language: csharp
solution: Unosquare.Tubular.Lib.sln
notifications:
  slack: unolabs:cbusXPH6pBwZ35rVDzi4k4ve
matrix:
  include:
    - os: linux
      mono: latest
      node_js: latest
      dist: trusty
      sudo: false
    - os: linux
      mono: latest
      node_js: latest
    - os: osx
      mono: latest
      node_js: latest
install:
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then brew cask install google-chrome; fi
  - nuget install NUnit.ConsoleRunner -OutputDirectory testrunner
  - nuget restore Unosquare.Tubular.Lib.sln
  - npm install
before_script:
  - touch ./src/Unosquare.Tubular/Javascript/tubular-bundle.js
  - touch ./src/Unosquare.Tubular/Javascript/tubular-bundle.min.js
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then export DISPLAY=:99.0; fi
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi
script:
  - xbuild /p:Configuration=Release Unosquare.Tubular.Lib.sln
  - mono --debug ./testrunner/NUnit.ConsoleRunner.*/tools/nunit3-console.exe --process=Single ./test/Unosquare.Tubular.Tests/bin/Release/Unosquare.Tubular.Tests.dll
  - npm test
